name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code with Compound Learning
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Enhanced prompt for compound learning integration
          prompt: |
            @claude Please address the user's request while applying our 4-criteria compound learning approach:

            ✅ **Correctness**: Ensure your solution is logically sound and error-free
            ✅ **Completeness**: Address all aspects of the user's request thoroughly  
            ✅ **Size**: Provide appropriately sized solutions (not over/under-engineered)
            ✅ **Trajectory**: Contribute to compound learning and knowledge building

            ## Compound Learning Integration

            When responding to the user's @claude request:

            1. **Apply Learning Standards**: Use established patterns from CLAUDE.md and ADRs
            2. **Consider Previous Context**: Reference related learnings and decisions where relevant
            3. **Document Insights**: If your work generates reusable patterns, consider using `/capture_learning`
            4. **Check ADR Compliance**: Use `/adr_check` if making architectural changes
            5. **Link Knowledge**: Use `/adr_link` to connect new insights with existing decisions

            ## 4-Criteria Response Framework

            - **Correctness**: Validate your approach against established best practices
            - **Completeness**: Ensure you've addressed all implicit and explicit requirements
            - **Size**: Choose the right level of detail and complexity for the request
            - **Trajectory**: Explain how your response builds on or contributes to our compound learning

            Now please respond to the user's original request with this enhanced context.

          # Enable compound learning tools
          claude_args: '--allowed-tools "Read,Edit,MultiEdit,Write,Glob,Grep,LS,Bash(gh:*),Bash(git:*),TodoWrite,Task"'

