name: Renovate

on:
    # Zeitplan: Jeden Tag um 3 Uhr morgens
    schedule:
        - cron: '0 3 * * *'
    # Manueller Trigger
    workflow_dispatch:

jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Self-hosted Renovate
              uses: renovatebot/github-action@v39.0.1
              with:
                  token: ${{ secrets.RENOVATE_TOKEN }}
              env:
                  LOG_LEVEL: 'debug'
                  RENOVATE_REPOSITORIES: ${{ github.repository }}
                  RENOVATE_PLATFORM: 'github'
                  RENOVATE_ONBOARDING: 'false'
                  RENOVATE_COMPOSER_VERSION: '2'
                  RENOVATE_BRANCH_PREFIX: 'renovate/'
                  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
                  RENOVATE_DRY_RUN: 'false'
                  RENOVATE_REQUIRE_CONFIG: 'optional'
                  RENOVATE_BASE_BRANCHES: 'main,master,develop,dev'